spring:
    profiles: test
name: test-YAML
environment: test
servers:
    - www.abc.test.com
    - www.xyz.test.com

---
spring:
    profiles: prod
name: prod-YAML
environment: production
servers:
    - https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/2
    - https://jsonplaceholder.typicode.com/todos/3
    - https://jsonplaceholder.typicode.com/todos/4
    - https://jsonplaceholder.typicode.com/todos/5
    - https://jsonplaceholder.typicode.com/todos/6
    - https://jsonplaceholder.typicode.com/todos/7
    - https://jsonplaceholder.typicode.com/todos/8